/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ColumnRouteImport } from './routes/$column'
import { Route as IndexRouteImport } from './routes/index'

const ColumnRoute = ColumnRouteImport.update({
  id: '/$column',
  path: '/$column',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$column': typeof ColumnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$column': typeof ColumnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$column': typeof ColumnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$column'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$column'
  id: '__root__' | '/' | '/$column'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColumnRoute: typeof ColumnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$column': {
      id: '/$column'
      path: '/$column'
      fullPath: '/$column'
      preLoaderRoute: typeof ColumnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColumnRoute: ColumnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
